### ISSUE TITLE
Update for Book Dupe / Chunk Saving Glitch

### ISSUE THREAD

**Issue by blockswerker** [dniym/IllegalStack#100]
I found an addendum from 2019 re: garbage characters in books. These books are used to overload a chunk and facilitate a dupe. The settings mentioned (see link below) are not in the default Illegalstack config, and the addendum recommends adding them, which I've done. I've reloaded the config in-game and restarted my server but the offending books are not effected.

Are there updated instructions for removing these books?

https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/update?update=252989

**Comment by dniym** [comment]
What version of Minecraft are you running? If this option does not appear in your config it is likely the dupe does not affect your version of spigot

**Comment by blockswerker** [comment]
It's Paper-387 running Minecraft 1.15.2.

**Comment by dniym** [comment]
The chunk overload dupe was fixed on the Minecraft side in 1.15 so the protection auto disables.

**Comment by blockswerker** [comment]
Interesting, because my players are definitely engaging in it!

**Comment by dniym** [comment]
This is probably the new book dupe that has recently surfaced, and turning on the chunk overload dupe protection won't do anything to prevent it.

if they are abusing the new one (which affects 1.13-1.16.4) 
you should have messages like this in your console:

[19:58:56] [Server thread/ERROR]: Failed to save player data for <username>

they would also disconnect.   If this is the case those players are using a hacked client which sends a special packet which crashes the client and prevents the inventory from saving.

You should be able to search your log files for "Failed to save player data for"  and you'll immediately know which players have been duping and can roll them back / ban them.   Pretty crappy dupe when it tells on the player for doing it.

In the meantime I would suggest you enable the disable all books protection until a better fix can be found, it's probably going to require blocking the malformed packet which is typically something IllegalStack does not deal with.   

To enable this feature use the following command: /istack toggle DisableBookWriting

This *SHOULD* prevent them from being able to create books period until a better fix is found.

**Comment by Ezzer29** [comment]
BRUH, rly, new book dupe?! Do u guys have some more info about it? I play on an anarchy server where there weren't any major dupes in the last 2 years (the server runs paper 1.13.2). The admins patch the dupes really quick, so if you would be kind enough to tell me more about the dupe it would be really helpful, anyway, thx :smiley:

**Comment by dniym** [comment]
https://youtu.be/1agB946DTa0

**Comment by s1h4d0w** [comment]
Just saw this in my chat, seems like it's working. MC 1.12 with IllegalStack 2.2.1a:
![image](https://user-images.githubusercontent.com/5654654/108284745-182b9d80-7186-11eb-8054-7019e4a278ef.png)

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
