### ISSUE TITLE
[Bug] Config Broken or 1 Config Option Is

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [dniym/IllegalStack#101]
The config has this option:
`  Nether:
    BlockPlayersAboveNether: true`
I tried disabling it twice now. The last time I made 100% sure I saved the file & restarted the server. It still shows up as 'true' though when I re-open the file & players/I cannot access the top of nether....
https://gyazo.com/47d65fb368635efc82f88960dd20751f

Paper 1.16.4
IllegalStack-2.2.0e

Please fix! Thanks you!

**Comment by dniym** [comment]
If you are editing config.yml manually with the server running you MUST do /istack reload BEFORE restarting the server. 


Alternatively you can configure the whole plugin in game with the /istack prot command.  

Or 
/istack toggle BlockPlayersAboveNether

If you use the in game commands there is no need to restart or reload the config

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> If you are editing config.yml manually with the server running you MUST do /istack reload BEFORE restarting the server.
> 
> Alternatively you can configure the whole plugin in game with the /istack prot command.
> 
> Or
> /istack toggle BlockPlayersAboveNether
> 
> If you use the in game commands there is no need to restart or reload the config

With Pterodactyl editing the file while the server is running shouldn't matter. If it does, this is the first plugin I've ever used in 4 years that required it.

However, thanks for the information. That fixed it.

**Comment by dniym** [comment]
It definitely matters because when the server restarts IllegalStack writes the in memory version of the config to the config.yml, if you don’t invoke /istack reload before restarting the manual changes never get loaded into memory and will be overwritten.
