### ISSUE TITLE
2 Questions: How do I disable it in a specific world, and why isn't it blocking hacks items like swords, spawn, and potions?

### ISSUE THREAD

**Issue by WalrusSlayer** [dniym/IllegalStack#102]
2 Questions: How do I disable it in a specific world, and why isn't it blocking hacked items like swords, spawn, and potions?

I need to block 100% of saved toolbars and op me books as well.

Thanks.

**Comment by dniym** [comment]
If you are editing config.yml manually with the server running you MUST do /istack reload BEFORE restarting the server.

Alternatively you can configure the whole plugin in game with the /istack prot command

If you use the in game commands there is no need to restart or reload the config
