### ISSUE TITLE
The dev builds link is dead

### ISSUE THREAD

**Issue by rautamiekka** [dniym/IllegalStack#103]
Dunno since when, but http://ci.athion.net/ doesn't host Illegal Stack anymore.

Couldn't find one which is. Even https://ci.codemc.io/ doesn't.

**Comment by dniym** [comment]
Not sure it’s ever was hosted there. It’s very rare I have dev builds the current one is always on spigots site

**Comment by rautamiekka** [comment]
Fair enough. Might wanna mention that in both places.
