### ISSUE TITLE
People are able to spawn in 

### ISSUE THREAD

**Issue by WalrusSlayer** [dniym/IllegalStack#106]
Fireworks that lag the server, zcar bombs, sticks that spawn giant withers, shulker boxes (should be disabled), etc.

I have configured everything I can find, and previous responses haven't helped. 

Please tell me how to disable this, or better yet, all saved toolbar items, and any not default enchantment.

Thanks!

**Comment by dniym** [comment]
https://github.com/dniym/IllegalStack/wiki/BlockBadItemsFromCreativeTab
