### ISSUE TITLE
Constantly  errors "Failed to predict insert ；not an IItemhandler" in console

### ISSUE THREAD

**Issue by blacksheep-lzx** [dniym/IllegalStack#111]
Maybe related MEK
![TIM图片20210213140735](https://user-images.githubusercontent.com/68332442/107843281-d5c03480-6e04-11eb-8181-79d932edeb72.png)

**Comment by dniym** [comment]
This is not part of IllegalStack's code.  It looks like according to the class name it's a plugin called Mekanism
