### ISSUE TITLE
Option to blacklist certain items from being placed in Shulker Boxes and Ender Chests

### ISSUE THREAD

**Issue by AfkF24** [dniym/IllegalStack#114]
Basically what the title suggests. Would be pretty useful in various situations.
I'm primarily looking at Shulker Boxes in this case, as they can be used as a moving inventory.

Cheers

**Comment by dniym** [comment]
Sorry for the very late reply to this, if you still would like to see this feature added please re-submit it.   Just trying to do some cleanup of old issues.
