### ISSUE TITLE
Illegal stack of items removed - in hand item turned into brought item

### ISSUE THREAD

**Issue by BendyGeek** [dniym/IllegalStack#122]
I am facing wired issue with Illegalstack plugin Recently we started using shopgui plugin there is random chance i will get message "[IllegalStack] -Illegal stack of items removed: BEETROOT_SOUP (10) from player: ThakurZ at item scan."

and what will it do replace in hand item with brought item from shop lets see carrot if player buy 16 carrots from shop then his sword (in hand item) will turned to 16 carrots and he cant eat carrots nor use in hand item he need to throw that item on group and then it will be converted back to normal sword after words.

There isnt any error log anything except above console error.

Using latest version of Illegalstack and shopgui plugin 
server running on paperspigot 1.16.4

**Comment by dniym** [comment]
IllegalStack is removing beetroot soup because it is a larger stack size than vanilla allows.  

The proper way to fix this is to set ShopGui to unstack these items in the config. 

https://docs.brcdev.net/#/shopgui/stack-size

**Comment by BendyGeek** [comment]
Thanks for quick reply 

Issue has been resolved.
