### ISSUE TITLE
[Suggestion] Found a dupe with shulkers 

### ISSUE THREAD

**Issue by Billabomb75** [dniym/IllegalStack#125]
Please see the video. I have tested this on a normal Spigot server and it works 100%.

https://vm.tiktok.com/ZSJ4Cq5D5/

Can you patch this for 1.17 please?

**Comment by dniym** [comment]
Looks like this is patched as of newer spigot 1.17 builds.

**Comment by Billabomb75** [comment]
Yup Paper Patched it
