### ISSUE TITLE
Edit file

### ISSUE THREAD

**Issue by Loqed44** [dniym/IllegalStack#130]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.2
- Spigot/Paper Version Number (`/version`): 1.17-R0.1-SNAPSHOT Paper
- Output of `/version`: Latest version

**Describe the bug**
Its not possible to edit a file when i want to edit the file in console and i restart the server it will be put back to the default file. 

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
Whenever you edit config.yml manually with the server running you MUST do /istack reload BEFORE restarting the server or changes will be lost. 

https://github.com/dniym/IllegalStack/wiki/How-do-I-edit-the-configuration%3F
