### ISSUE TITLE
[IllegalStack/pLisbListener] Async Packet - Couldn't get an entity from id: 

### ISSUE THREAD

**Issue by Achent007** [dniym/IllegalStack#132]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.2
- Spigot/Paper Version Number (`/version`): git-Paper-1618 (MC: 1.12.2)
- Output of `/version`: Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Describe the bug**
When i click on a NPC with attached command i got my console spammed by one error ([https://pastebin.com/xnaVf0uj](https://pastebin.com/xnaVf0uj))

**To Reproduce**
1. have Citizens with player trait and custom name (like colored name)
2. click on a NPC
3. Error happend

**Plugins being used on the server**

Plugins (105): AAC5, AntiDrop, AntiWDL, AreaShop, ArmorStandTools, BankNotes, BarAPI, BarGamble, BattlePass, BeerChance, BeerTokenBar, BeerTreasure, BetterChairs, BossShopPro, BuycraftX, ChatColor2, ChatReaction, ChestShop, Citizens, CMI, CMILib, CoinFlipper, CommandNPC, CoreProtect, CrazyEnvoy, CustomPayloadFixer, DamageEnderPearl, DeluxeTags, Duels, EasyEnderPearlCooldown, EditableSign, EnderPearlWorld, EZBlocks, eZProtector, FastAsyncVoxelSniper, FastAsyncWorldEdit, FastPot, goBrush, goPaint, HeadDatabase, helper, HelpPages, HideAchievements, HideAndCustomPlugins, HolographicDisplays, HolographicPlaceholders, IllegalStack, InfiniteVouchers, Insights, InvenCheck, InventoryRollbackPlus, Item2Chat, ItemEdit, JumpPads, KOTH, LeaderHeadsRevamped, LiteBans, LuckPerms, Maintenance, MessageAnnouncer, MineCrates, MobArena, MoneyNote, Multiverse-Core, MyCommand, NBTAPI, OpenInv, PlaceholderAPI, PlayerVaults, PlotSquared, PlugMan, PremiumVanish, ProQuests, ProtocolLib, RealPing, RightClickSneak, ServerListMotdSpigot, ServerSigns, Shopkeepers, spark, SpecializedCrates, StaffChat, SuperTrailsPro, TAB, TigerReports, TigerReportsSupports, TitleManager, TntBreak, TradeMe, UltraPrisonCore, Vault, ViaBackwards, ViaRewind, ViaVersion, VillagerFight, VoteParty, Votifier, VoxelSniper, VPNGuard, WorldEdit, WorldGuard, WorldGuardExtraFlags, XLAutoMiner, XLTournaments, zAuctionHouseV3

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by cod-eon** [comment]
up. I also ran into this problem. does anyone have any ideas on how to solve it?

**Comment by cod-eon** [comment]
If you are using version 1.12.2, then install Illegal Stack v2.4.2 (https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/download ?version=422051).
