### ISSUE TITLE
DamagePlayersAboveNether at whole Nether

### ISSUE THREAD

**Issue by Marv2190** [dniym/IllegalStack#134]
**Required Information**
- FAVS Version Number (`/version IllegalStack`):
-  IllegalStack version 2.4.2
- Spigot/Paper Version Number (`/version`):
- Spigiot 
- Output of `/version`:
CraftBukkit version 3231-Spigot-3c1fc60-e167f28 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Describe the bug**
If BlockPlayersAboveNether is true, players EVERYWHERE in the nether getting the Damage, not only above the CeilingBedrock

**To Reproduce**
Set DamagePlayersAboveNether to true - go into the Nether WITHOUT OP

**Plugins being used on the server**
LoginSecurity
IllegalStack
dynmap
DeadChest
CoreProtect
ChestSort

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [x] I made sure the bug/error is not caused by any other plugin (as good as i could)

**Comment by Marv2190** [comment]
Hi,
 NetherYLevel: 128

Players are ~78.

**Comment by dniym** [comment]
Hmm why -78???
Try To enable / disable this protection use the following command: /istack toggle KillPlayersBelowNether

**Comment by Marv2190** [comment]
nonono :) not -78, ~(around) 78

**Comment by PerchunPak** [comment]
same

**Comment by Hydr4gyrum** [comment]
I encountered this problem as well
Block players above nether works pretty well, but it doesnt stop elytras

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
