### ISSUE TITLE
1.17.X+ Shulker

### ISSUE THREAD

**Issue by Pandas0** [dniym/IllegalStack#136]
**Is your feature request related to a problem? Please describe.**
Minecraft 1.17 added a chance for a shulker to spawn a new shulker if hit by it's projectile (shulker bullet). This has resulted in shulker shells, in my opinion, becoming way too common and made end exploring nearly useless.

This has resulted in players on my server making over 250 shulker boxes within just a few hours with an extremely small farm.

**Describe the solution you'd like**
I would like, if possible, for you to maybe add a configuration option to either nerf these automatic shulker farms (Links in the additional context) or the ability to completely disable shulker's from shooting each other.

**Describe alternatives you've considered**
I've considered using an entity chunk limiter, but these farms work with just 1 "activator" shulker and I've only seen like 5-6 shulkers at one time in the farm. The limiter could also cause issues with natural shulkers in the end structures, which I am not trying to affect.

**Additional context**
Examples of the farm: 

1: https://www.youtube.com/watch?v=pFdLqTE1MzE&t=0s [The farm being used on my farm]
2: https://www.youtube.com/watch?v=ynvoyDehf1Q
3: https://www.youtube.com/watch?v=RRSnya62snY

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still need this feature please re-open this ticket.   Apologies for taking so long to address it.
