### ISSUE TITLE
Beds in the end/nether exploding is being detected

### ISSUE THREAD

**Issue by HAHALOSAH** [dniym/IllegalStack#137]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.2a
- Spigot/Paper Version Number (`/version`): 3265-Spigot-3892929-fd50041
- Output of `/version`: This server is running CraftBukkit version 3265-Spigot-3892929-fd50041 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Describe the bug**
Beds that explode in the end and in the nether are being falsely detected
![image](https://user-images.githubusercontent.com/67280050/141663387-4389f588-09cf-48e3-8f4d-9d63cf138552.png)

**To Reproduce**
1. Go to the end/nether
2. Place bed
3. Right click

**Plugins being used on the server**
Not needed

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
This is working as designed, placing a bed in the end/nether then sleeping on it creates an explosion.    If im missing something here and it's still an issue with the latest version please re-open this ticket.
