### ISSUE TITLE
istack toggle command doesn't seem to work right 1.12.2

### ISSUE THREAD

**Issue by IITFA** [dniym/IllegalStack#14]
I'm on 1.12.2 Paper and the toggle command seems to do nothing.

> [15:31:59 INFO]: USERNAME issued server command: /istack toggle kickforautoclickerfishing
> [15:31:59 INFO]: [IllegalStack] -Protection: KickForAutoClickerFishing has been turned OFF by USERNAME
> [15:32:07 INFO]: [IllegalStack] -USERNAME is spam fishing! ~casts~ casts without a 2 second break! @ Location{world=CraftWorld{name=Biome Bundle},x=1552.3828448758406,y=57.0,z=2359.5325039331424,pitch=-16.903101,yaw=81.739075}
> [15:32:07 INFO]: USERNAME lost connection: Auto Clicker Fishing is not allowed on this server!
> [15:32:07 INFO]: USERNAME left the game

I manually edited the config file, did istack reload and it still kicks. I even shut down the server, edited the config file, started the server, and it still kicks.

**Comment by dniym** [comment]
are you still experiencing this issue?  What is the output of /istack ver?

**Comment by dniym** [comment]
Closing due to no response from OP
