### ISSUE TITLE
Bypass chest mob block

### ISSUE THREAD

**Issue by franxyk** [dniym/IllegalStack#140]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.2a
- Spigot/Paper Version Number (`/version`): 1.17.1

**Describe the bug**
on DisableChestsOnMobs: true, put chest into dispenser, You approach the mob and the dispenser with chests inside, it will place one on the mob, thus being able to evade the blockade.

**To Reproduce**
on DisableChestsOnMobs: true, put chest into dispenser, You approach the mob and the dispenser with chests inside, it will place one on the mob, thus being able to evade the blockade.

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
