### ISSUE TITLE
java.lang.RuntimeException: Cannot retrieve entity from ID. (paper 1.17.1)

### ISSUE THREAD

**Issue by Spiderjockey02** [dniym/IllegalStack#141]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): IllegalStack version 2.1.4a
- Spigot/Paper Version Number (`/version`): Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
- Output of `/version`: same as above

**Describe the bug**
This huge error block: https://sourceb.in/nmYD1CWNdo

**To Reproduce**
Steps to reproduce the behaviour:
1. Don't really just occur randomly

**Plugins being used on the server**
Plugins (42): AsyncWorldEdit, AuctionHouse, BeastWithdraw, BountyHunters, BuycraftX, ChatControl, ChatReaction, Citizens, ClearLag, CoreProtect, CosmicVaults, CrazyCrates, CrazyEnchantments, DeluxeMenus, EpicHoppers, EpicSpawners, EpicVouchers, Essentials, EssentialsProtect, EssentialsSpawn, FabledSkyBlock, GUIShop, HolographicDisplays, IllegalStack, InteractiveChat, KeepDeathDrop, KitPreview, LootChest, LuckPerms, NerfPhantoms, PlaceholderAPI, Plan, ProtocolLib, ServerSelectorX, TabList, UltimateStacker, Vault, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [?] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [?] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
