### ISSUE TITLE
PreventInfiniteElytraFlight should not block player using elytra bellow 320 blocks height in 1.18 servers

### ISSUE THREAD

**Issue by eternitymoe** [dniym/IllegalStack#142]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): IllegalStack version _2.4.2_ **I comfirm it's actually the version 2.4.4. It appears that the build on Spigot does not change (forgotten?) the version number :P**
- Spigot/Paper Version Number (`/version`): Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
- Output of `/version`:
[12:30:51 INFO]: Checking version, please wait...
[12:30:51 INFO]: This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
You are running the latest version
Previous version: git-Paper-152 (MC: 1.18.1)

**Describe the bug**
PreventInfiniteElytraFlight should block player using elytra above 256 blocks height in 1.18 servers

**To Reproduce**
Using IllegalStack in a 1.18 server and turn on PreventInfiniteElytraFlight check

**Checklist**:

- [*] I included all information required in the sections above
- [*] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [*] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [*] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
Hmm ill have to do some investigating on how to address this...   It appears you can also go -64 blocks past zero legally as well?

**Comment by dniym** [comment]
Also do we know if Infinite Elytra Flight is still an issue?

**Comment by In77** [comment]
> Also do we know if Infinite Elytra Flight is still an issue?

No. It seems be fixed in 1.16.

PS: actually I haven't changed the config about those setting since 1.14.4
Then my player told me the other day that they couldn't use elytra above 256 blocks
In fact, I should confirm the glitch first and then report back, but I didn't think much about it.
😂
