### ISSUE TITLE
Shulker+Dispenser=Unlimited items？ （It may be an article replication vulnerability caused by the IllegalStack）

### ISSUE THREAD

**Issue by luoxiawuchen** [dniym/IllegalStack#143]
**Required Information**
- FAVS Version Number (`/version IllegalStack`):
- Spigot/Paper Version Number (`/version`):2.4.4
- Output of `/version`:
![image](https://user-images.githubusercontent.com/64759847/149911291-ecdd82e4-c6c7-4b46-9d7e-0161aeab5847.png)

**Describe the bug**
![image](https://user-images.githubusercontent.com/64759847/149911600-7d979d65-882f-40dc-8d4d-ce61cf7dd224.png)
![image](https://user-images.githubusercontent.com/64759847/149911644-ed52ea10-f165-487e-8348-6d2268c2345a.png)
![image](https://user-images.githubusercontent.com/64759847/149913825-86aebb4e-f603-4628-9d6e-4a65cc17af5e.png)
Shulker+Dispenser=Unlimited items

1、InstallI llegalStack plugins
2、As shown in the picture above, put the shulker with items into the dispenser and activate the transmitter with the red stone signal to copy a shulker
3、Under normal circumstances, the latent image box should be emitted as a block rather than an item

**To Reproduce**
1、InstallI llegalStack plugins
2、As shown in the picture above, put the shulker with items into the dispenser and activate the transmitter with the red stone signal to copy a shulker
3、Under normal circumstances, the latent image box should be emitted as a block rather than an item

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [] I made sure the bug/error is not caused by any other plugin

In fact, I think this is a fatal bug. My English is not very good. Thank you for your patience

**Comment by dniym** [comment]
So far I have been unable to reproduce this bug.

I've tried on a Paper 1.16.5 server as well as a regular Spigot 1.16.5 both with illegalstack 2.4.4
The shulker dispenses as expected.

1) are you getting any errors in the console when you do this?
2) can you try to reproduce this behavior without any other plugins besides IllegalStack and your server.jar file?

Being that you're using Mohist / Forge I can't guarantee that IllegalStack will work on that as it is completely untested on my end.

**Comment by luoxiawuchen** [comment]
> So far I have been unable to reproduce this bug.
> 
> I've tried on a Paper 1.16.5 server as well as a regular Spigot 1.16.5 both with illegalstack 2.4.4 The shulker dispenses as expected.
> 
> 1. are you getting any errors in the console when you do this?
> 2. can you try to reproduce this behavior without any other plugins besides IllegalStack and your server.jar file?
> 
> Being that you're using Mohist / Forge I can't guarantee that IllegalStack will work on that as it is completely untested on my end.

Oh, thank you for your reply
Maybe I should test on the spigot side first and then give feedback
This should be a problem only in Mohist or similar server-side environment
I'm testing the contents of the configuration file one by one
It will take some time

**Comment by rustjunky** [comment]
This is happening on my server.

**Comment by blockswerker** [comment]
I'm researching this on my own server right now, running 1.17.1. Here's a video of it in action:

https://www.youtube.com/watch?v=oG85ApbyhTY
