### ISSUE TITLE
PearlPhasing works as described but doesn't block glitching through glass panes

### ISSUE THREAD

**Issue by Tiippex** [dniym/IllegalStack#144]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.5
- Spigot/Paper Version Number (`/version`): git-Paper-168 (MC: 1.18.1)
- Output of `/version`: This server is running Paper version git-Paper-168 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: dcca6cb)

**Bug description**
When throwing an ender pearl right under the glass pane it is possible to glitch through it when holding W during that.

Without holding W it does not work. I created a short clip here:
https://user-images.githubusercontent.com/16509128/150646716-3ae2ec09-101c-48bc-9afd-b47b824b80d8.mp4

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
