### ISSUE TITLE
Doesn't Remove Illegal Items When In Offhand

### ISSUE THREAD

**Issue by ItsMCB** [dniym/IllegalStack#145]
**Required Information**
2.4.5
git-Purpur-1547 (MC: 1.18.1)*

**Describe the bug**
Illegal items aren't removed when they are taken from a hotbar and placed right into the offhand.
![](https://i.imgur.com/p22t688.png)

**To Reproduce**
1. Download a hotbar.nbt file with illegal items and place it in your Minecraft folder
2. Open a server with the latest version of IllegalStack on it
3. Take the item from the hotbar, click "Survival Inventory" (chest icon) to go back into the creative player menu w/ all slots, place in the offhand / shield slot.
4. Check console to see output that spams a message claiming to have removed the item from the player.

**Plugins being used on the server**
AnimatedScoreboard, BKCommonLib, Citizens, City, CMI, CMILib, CommandPrompter, CoreProtect, DeluxeMenus, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), goBrush, HeadDatabase, IllegalStack, LiteBans, LuckPerms, MineSecure*, My_Worlds, PlaceholderAPI, Plan, PlotSquared, ProtocolLib, SelectionVisualizer, UltraCustomizer, Vault, ViaBackwards, ViaVersion, VoidGen, WorldGuard & additional custom plugins.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
