### ISSUE TITLE
MMOITEMS and ORAXEN plugin support. 

### ISSUE THREAD

**Issue by Keopsfenks** [dniym/IllegalStack#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
NONE

**Describe alternatives you've considered**
Like Slimefun, does mmoitems and oraxen support come? 

**Additional context**
NONE

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you this is still needed please open a new ticket and I will look into it.
