### ISSUE TITLE
Full Hopper Minecarts Below Full Chests Causes Extreme Lag (Effective Lag Machine)

### ISSUE THREAD

**Issue by KyGuy2002** [dniym/IllegalStack#149]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.5
- Spigot/Paper Version Number (`/version`):
- Output of `/version`: 1.17.1, Paper-408

**Describe the bug**
Hopper check causes a ton of stress on the server when using a simple machine.
Simply making 4 or 5 of these simple machines with any item can bring tps down to 10.  Currently you need to set the “disable-hopper-check” config option to true to prevent this from happening.

**To Reproduce**
By placing a hopper minecart with a completely full inventory, and then having a double chest that’s also completely full above it you can cause server lag.

**Plugins being used on the server**
No effect, as disabling the hopper check completely fixes this issue.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by KyGuy2002** [comment]
It seems that this is a paper issue, and i have opened an issue [issue](https://github.com/PaperMC/Paper/issues/7582) on their repo.  The InventoryMoveItemEvent seems to fire even if the transfer failed, but only for hopper minecarts.

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
