### ISSUE TITLE
Permission Node for teleporting?

### ISSUE THREAD

**Issue by jakkuh** [dniym/IllegalStack#15]
When a mod clicks the teleport on IllegalStack alerts they're told they have insufficient permissions. I found that command as shown below, but there doesn't appear to be a permission node for this?

`/istack teleport 5712 67 -5912 world`

**Comment by dniym** [comment]
Typically players need the   illegalstack.admin permission to use the features of IllegalStack, this would include being able to teleport to coordinates.    Generally I would not recommend giving this permission out to staff unless you completely trust them as they will be able to turn off / edit protections.  Please let me know if this helps your issue if satisfied please close it once you've read this.

**Comment by jakkuh** [comment]
Can you add in a permission node for teleporting so I can allow mods to be able to use the teleport command without having to give them full perms to everything istack related?

**Comment by dniym** [comment]
this will be added in the next update as long as they have illegalstack.notify they can teleport.
