### ISSUE TITLE
[Prevent End Crystal Lag Machine] also prevents an entity from being pushed into another entity

### ISSUE THREAD

**Issue by SideLo98** [dniym/IllegalStack#150]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.4.5
- Spigot/Paper Version Number (`/version`): Pufferfish build 56 (1.18.2)
- Output of `/version`: 
![image](https://user-images.githubusercontent.com/67060780/159638812-bbb35d02-1b2c-426a-8673-3e86dd216f1a.png)

**Describe the bug**
![image](https://user-images.githubusercontent.com/67060780/159639066-1705d886-e982-4eea-8431-8294d1bd3ea8.png)
![image](https://user-images.githubusercontent.com/67060780/159639085-2f999e2d-9eb3-4f01-b4e1-f8484b0f0a03.png)

Doing this thing in above ^ image is prevented by this protection below.

![image](https://user-images.githubusercontent.com/67060780/159639214-6d2d5534-ecc4-4e2c-ae0b-05b92f3c61bb.png)

although it has nothing to do with end crystal. I think [Prevent End Crystal Lag Machine] should have options to control which blocks to whitelist/blacklist OR move this settings to [Prevent Armor Stand Lag Machine] OR [Prevent Minecart Glitching] as it prevents Glass_Blocks being pushed into armor stand.

**To Reproduce**
1. first turn [ON] [Prevent End Crystal Lag Machine]
2. place armor stand give it armor or not doesnt matter
3. place piston above it as shown in image above and move glass blocks inside armor stand
4. it won't let you place glass in armor stand and give warning "prevented an entity (armor stand/end crystal/minecart) from being pushed into another entity @ cords"
5. this protection itself is fine no issue with protection but it should be in either [Prevent Armor Stand Lag Machine] OR [Prevent Minecart Glitching] OR an option in [Prevent End Crystal Lag Machine] to whitelist/blacklist armor stand/end crystal/minecart because I want use end crystal lag machine protection at the same time with glass pushing in armor stand as well.

**Plugins being used on the server**

I use over 100 plugins but if it's still needed let me know in comments.

**Checklist**:

- [✓] I included all information required in the sections above
- [✓] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [✓] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [✓] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
