### ISSUE TITLE
the portal does not open at an altitude of more than 256

### ISSUE THREAD

**Issue by igumen1990** [dniym/IllegalStack#151]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): Illegal Stack (2.4.5)
- Spigot/Paper Version Number (`/version`): git-Paper-259 (MC: 1.18.2) 
- Output of `/version`: This server is running Paper version git-Paper-259 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2eeca6f)

**Describe the bug**
plugin does not allow to light the portal to the lower world at a height of 256. 
at an altitude below 256, the portal opens normally

**To Reproduce**
1. soar to a height of more than 256 in the upper world
2. build a portal to the underworld
3. ignite the portal
4. the fire burns, the portal does not open

**Plugins being used on the server**
When the plugin is disabled, everything works as it should.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
