### ISSUE TITLE
Slimefun

### ISSUE THREAD

**Issue by WongIong** [dniym/IllegalStack#152]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): IllegalStack version 2.4.5
- Spigot/Paper Version Number (`/version`): Paper-411 1.17.1
- Output of `/version`: 

**Describe the bug**
https://pastebin.com/HCRHkjWT

**To Reproduce**
1. install the plugin

**Plugins being used on the server**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
are you on the discord for illegalstack by chance?   I should have this fixed but would like to test it on a slimefun enabled server.   If you could contact me via discord i'll send you an updated version to verify the issue is resolved.

**Comment by WongIong** [comment]
Yes i do in discord, also i did report that something is not working recently :)
i will dm you

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
