### ISSUE TITLE
DisableInWorlds doesnt seem to TripWireDupe check

### ISSUE THREAD

**Issue by LogGits** [dniym/IllegalStack#157]
**Required Information**
- FAVS Version Number (`/version IllegalStack`): 2.5
- Spigot/Paper Version Number (`/version`): git-Paper-134 (MC: 1.19.2)
- Output of `/version`:

**Describe the bug**
DisableInWorlds doesn't apply for tripwire hook dupe protection. Want to disable this in build world. Ideally DisableInWorlds should entirely disable illegalstack protections in that world.

**To Reproduce**
- add worldname to file.
- restart
- place tripwire hook to trigger dupe protection

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dniym** [comment]
Working on a fix for this but it's a bit more tricky than expected.

**Comment by dniym** [comment]
Fixed in IllegalStack 2.9 
(***WARNING***) disabling this check if you use a crate key plugin may allow players to dupe your crate keys!   You have been warned.
