### ISSUE TITLE
Items will not have their durability value deducted

### ISSUE THREAD

**Issue by ZhangMouQWQ** [dniym/IllegalStack#158]
**Required Information**
- FAVS Version Number (`/version IllegalStack`):IllegalStack-2.7.1.jar
- Spigot/Paper Version Number (`/version`):CatServer-1.16.5-a76056a9-server.jar (Bukkit) #Maybe this plugin doesn't work here?
- Output of `/version`:This server is running CatServer version 1.16.5-a76056a9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

**Describe the bug**

Items will not have their durability value deducted

**To Reproduce**

 https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia
 After installing this plugin, the items in this mod will not have their durability value deducted

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/dniym/IllegalStack/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using an up-to-date version of [IllegalStack](https://www.spigotmc.org/resources/44411/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by ZhangMouQWQ** [comment]
If this plugin does not work on this server core, or is not mod compatible, please let me know.

**Comment by dniym** [comment]
I am not familiar with this plugin, but the only protection IllegalStack checks durability on is FixNegativeDurabilty

You may try turning this protection off with /istack toggle FixNegativeDurabilty and see if the issue still exists.   One other possibility might be FixIllegalEnchants as some plugins use invalid enchants and durabilities which IllegalStack may think are invalid items.   

In either case IllegalStack will give you a message in game or in console if it is taking any action, if you see it in the logs let me know which one is triggering and we can look into it further
