### ISSUE TITLE
Automatically disable Overstacking protections when using StackableItems

### ISSUE THREAD

**Issue by 4194304** [dniym/IllegalStack#173]
**Is your feature request related to a problem? Please describe.**
Today I installed this plugin and it instantly wiped half of my inventory when I logged on, so for people who use plugins that allow you to stack above the stacking limit this would be great

**Describe the solution you'd like**
Make it detect if [StackableItems](https://dev.bukkit.org/projects/stackableitems) is installed and immediately disable the overstacking protections if it is present.

**Describe alternatives you've considered**
Manually disabling overstack protections in the config, but this made absolutely no difference since my inventory had already been wiped

**Additional context**
N/A

**Comment by dniym** [comment]
This is a fair request, We personally don't use that particular plugin so it's not really an issue..   I'll put it on the todo list for next version.

**Comment by dniym** [comment]
HOWEVER;  If the stackableitems plugin dev had just programmatically increased the vanilla stack limits, IllegalStack would not have removed them.

**Comment by dniym** [comment]
[18:45:13 WARN]: [IllegalStack/IllegalStack] The StackableItems plugin has been detected on your server, The protection RemoveOverstackedItems has been automatically disabled to prevent item loss, enabling this protection will most definitely remove items as this plugin is known to break the vanilla stack limits.    

As of version 2.9.7 and above this warning will appear when it generates the default configuration.
