### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Attila144** [dniym/IllegalStack#19]
I keep on getting this to my console, is there any way that I can resolve it?

16.02 14:07:56 [Server] WARN [IllegalStack] Task #48 for IllegalStack v2.0.10b generated an exception
16.02 14:07:56 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInOffHand()Lorg/bukkit/inventory/ItemStack;
16.02 14:07:56 [Server] INFO at timers.fTimer.run(fTimer.java:155) ~[?:?]
16.02 14:07:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Multicraft] Skipped 32 lines due to rate limit (30/s)
16.02 14:07:57 [Server] WARN [IllegalStack] Task #48 for IllegalStack v2.0.10b generated an exception
16.02 14:07:57 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInOffHand()Lorg/bukkit/inventory/ItemStack;
16.02 14:07:57 [Server] INFO at timers.fTimer.run(fTimer.java:155) ~[?:?]
16.02 14:07:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
16.02 14:07:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by dniym** [comment]
What version of spigot are you running IllegalStack on?  Looks like whichever version does not have offhand support

**Comment by Attila144** [comment]
Tried the latest one, then I tried 2.0.10

**Comment by dniym** [comment]
No, I mean what version of Spigot/Minecraft is your server??  1.8?

**Comment by Attila144** [comment]
My server is 1.8

**Comment by dniym** [comment]
1.8.0? 1.8.2? 1.8.3? 1.8.4?

**Comment by dniym** [comment]
It appears you're running 1.8.1, the plugin was built against 1.8.3 but I have changed it to also support 1.8.1   Please let me know if there are any other problems:

https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/update?update=318428

IllegalStack version 2.0.10c should fix the console spam
