### ISSUE TITLE
I don't understand this

### ISSUE THREAD

**Issue by Attila144** [dniym/IllegalStack#22]
Server: Spigot 1.8.1

Is there a way to turn off the debugging?

Console Logging:
1.03 22:57:21 [Server] ERROR Could not pass event BlockPistonRetractEvent to IllegalStack v2.0.10c
01.03 22:57:21 [Server] INFO org.bukkit.event.EventException
01.03 22:57:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.e(BlockPiston.java:72) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.doPhysics(BlockPiston.java:44) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
01.03 22:57:21 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]

**Comment by Attila144** [comment]
I installed what you sent previously https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/update?update=318428 but I still get it.

**Comment by dniym** [comment]
This looks like a different bug, which is caused by a piston retracting somewhere in your world, probably a redstone machine.   There should be a mention of the line number in IllegalStack where the issue is occurring.    Could you please send me the whole log via pastebin.com? Or at least the entire error.

**Comment by Attila144** [comment]
I dont know if this helps

02.03 00:03:27 [Multicraft] Skipped 8113 lines due to rate limit (30/s)
02.03 00:03:27 [Server] ERROR Could not pass event BlockPistonRetractEvent to IllegalStack v2.0.10c
02.03 00:03:27 [Server] INFO org.bukkit.event.EventException
02.03 00:03:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.e(BlockPiston.java:72) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.doPhysics(BlockPiston.java:44) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:27 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]

02.03 00:03:32 [Server] INFO org.bukkit.event.EventException
02.03 00:03:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.e(BlockPiston.java:72) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.doPhysics(BlockPiston.java:44) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:32 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Multicraft] Skipped 7404 lines due to rate limit (30/s)
02.03 00:03:33 [Server] ERROR Could not pass event BlockPistonRetractEvent to IllegalStack v2.0.10c
02.03 00:03:33 [Server] INFO org.bukkit.event.EventException
02.03 00:03:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.e(BlockPiston.java:72) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockPiston.doPhysics(BlockPiston.java:44) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:533) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:33 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]

02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:534) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.e(BlockRedstoneWire.java:76) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:259) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.d(World.java:583) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.applyPhysics(World.java:531) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneTorch.remove(BlockRedstoneTorch.java:75) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.Chunk.a(Chunk.java:512) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.World.setTypeAndData(World.java:392) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.BlockRedstoneTorch.b(BlockRedstoneTorch.java:120) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:632) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:236) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:741) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:40 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [gametype_skyblock.jar:git-Spigot-b1e6da1-17962f6]
02.03 00:03:41 [Multicraft] Skipped 28987 lines due to rate limit (30/s)

**Comment by dniym** [comment]
Not really, the part where it’s skipping lines is probably where the Error lines of I need are. Could you send me a copy of the log file? Or if you open up the log file there will be a line somewhere in there that helps. It will be something probably like fListener.java if you wish to search for it

**Comment by Attila144** [comment]
Ok, sorry for wasting your time, it was on my side where I had to update the Spigot config which was causing other plugins to collide such as CoreProtect to mess it around

**Comment by dniym** [comment]
Ah okay! I was having a hard time finding where the error in IllegalStack was in that! Glad you got it sorted!

**Comment by Attila144** [comment]
So how i fixed this is by asking my host questions and one of the answers were since my spigot is 1.8.0 that was causing all of the bugs and issues
