### ISSUE TITLE
Spam in console with latest version.

### ISSUE THREAD

**Issue by Haczyn** [dniym/IllegalStack#28]
12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/118, uuid='8b2f2dd8-2917-45b7-bf0e-928641806beb', l='world_the_end', x=-1.41, y=72.39, z=-0.78, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/119, uuid='b271b60b-75c3-4e08-af01-9efbd7efc2ea', l='world_the_end', x=-0.79, y=72.44, z=-1.56, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/120, uuid='d350b77f-1d60-4fd6-bfb0-846560e6fa6d', l='world_the_end', x=2.36, y=72.42, z=-5.44, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/121, uuid='af9c9547-940d-4976-a7f4-3354d4d8fd05', l='world_the_end', x=4.78, y=74.60, z=-8.61, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/122, uuid='37d330bd-e3a6-4dca-a155-10db5379bc86', l='world_the_end', x=6.25, y=74.87, z=-9.97, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/123, uuid='054e2183-5374-45fa-a4b0-182b0d76dcd6', l='world_the_end', x=8.03, y=75.13, z=-11.00, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/124, uuid='1acde9c4-9b14-4a64-bcd9-f27d398fb807', l='world_the_end', x=-1.05, y=74.42, z=-8.42, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:42:13 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/125, uuid='edcdaabf-f0ff-46d0-a081-293344210fa8', l='world_the_end', x=6.33, y=74.42, z=-3.28, cx=0, cz=0, tl=0, v=false, d=false]
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
>.... [12:42:13 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>.... [12:42:13 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [12:42:13 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
>.... [12:42:13 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [12:42:13 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
>.... [12:42:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [12:42:13 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by dniym** [comment]
This is not related to IllegalStack. My plugin is not mentioned at all in that error.   EntityTrackerFixer from minemora perhaps?
