### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by dominikaaaa** [dniym/IllegalStack#32]
Hi, I couldn't find anywhere on spigot if it's open source or not, and the repo has a GPL license leading me to assume that it is?

**Comment by dniym** [comment]
The wiki is really the only thing on github, well that and the issues.  I’ve had some people ask for the source to be uploaded but truth is I’ve just been too lazy to set it up as a repo and maintain it.   I’ll try to look at doing that.

**Comment by dominikaaaa** [comment]
I see. Thanks for the quick response!
