### ISSUE TITLE
PreventPortalTraps enhancements 

### ISSUE THREAD

**Issue by AfkF24** [dniym/IllegalStack#34]
Add a config option to run a command as player when they get stuck in a portal, opposed to breaking it, i.e. `/spawn`.

**Comment by dniym** [comment]
this isn’t a bad idea, I will look into this later today.

**Comment by AfkF24** [comment]
Depending on if it can be actually implemented or not, another idea is to send a message to the player saying that the portal is trapped/blocked and send them back to their original one.

**Comment by dniym** [comment]
Yeah I can detect the portal is trapped when they try to go through it and just deny them entry easy enough.  But the issue is if a player is currently trapped then they log in inside the portal what then?

**Comment by AfkF24** [comment]
> Yeah I can detect the portal is trapped when they try to go through it and just deny them entry easy enough.

This would be great actually!

> But the issue is if a player is currently trapped then they log in inside the portal what then?

I'd make this as more of a fallback option, and that's where the execution of commands (eg. /spawn) would come into play. If not, simply leave it to break portals.

Players that are found like this have either:
1. been stuck in the portal even before this option was enabled in config (or plugin was installed)
2. have logged out and logged back in at the exact position of where a portal was spawned/created

**Comment by dniym** [comment]
Yeah it’s most likely scenario 1) where they’ve been trapped forever

**Comment by AfkF24** [comment]
Figured, yeah... The thing with simply breaking portals is that it's not really suitable for Factions servers, because you could basically let someone into your base (or whatever) that way; hence why I was suggesting on adding execution of commands as player.

I've updated my previous comment to include a tl;dr of everything I suggested here.

**Comment by dniym** [comment]
IMO factions should prevent players fro
 Even portaling into claimed land but I suppose that’s a totally different conversation

**Comment by AfkF24** [comment]
> IMO factions should prevent players fro
> Even portaling into claimed land but I suppose that’s a totally different conversation

Hard agree.

**Comment by AfkF24** [comment]
> Depending on if it can be actually implemented or not, another idea is to send a message to the player saying that the portal is trapped/blocked and send them back to their original one.
> 
> Would feel much smoother and you wouldn't be getting the "what just happened" effect. If not, some kind of a message would still be very welcome :)

> Yeah I can detect the portal is trapped when they try to go through it and just deny them entry easy enough. But the issue is if a player is currently trapped then they log in inside the portal what then?

Well, I guess this was implemented long time ago :)

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
