### ISSUE TITLE
PearlPhasing doesnt work

### ISSUE THREAD

**Issue by kinrokinro** [dniym/IllegalStack#38]
Hello, PearlPhasing doesnt work when i try to bypass glass (not glass pane).
1.15 paper 260

Regards.

**Comment by dniym** [comment]
Hmmm did you edit the config manually? And are sure the protection is on?   /istack prot in game will show you what’s on/off

**Comment by kinrokinro** [comment]
![изображение](https://user-images.githubusercontent.com/3493914/81401313-bee30800-9137-11ea-8319-9f17c22d2179.png)
![изображение](https://user-images.githubusercontent.com/3493914/81401339-cbfff700-9137-11ea-9178-dbc6c6f061f2.png)
Yes, thats on

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
