### ISSUE TITLE
PreventPortalTrap

### ISSUE THREAD

**Issue by x1p** [dniym/IllegalStack#39]
On a skyblock server a portal was shut off because blocks are to close to the portal
```
  NetherPortal:
    PreventPortalTrap: true
```
In this case I think istack could have overreacted a bit. On my server, blocked portals are not really an issue, so I'll turn it off.

But for the sake of improving this protection, I'll give details.
![2020-05-09_11 54 35](https://user-images.githubusercontent.com/28690790/81470894-adf4ce00-91ed-11ea-8e12-23320869be7e.png)
On one side: you see fence gates. The full block beneath it are on the same level as the obsidian.
![2020-05-09_11 54 41](https://user-images.githubusercontent.com/28690790/81470896-ae8d6480-91ed-11ea-9095-030d60150d9d.png)
The other side is probably the issue. There are normal fences on slabs. The slabs are half a block above the obsidian.
So the player can leave on one side.
I reproduced it by making this:
![2020-05-09_12 14 22](https://user-images.githubusercontent.com/28690790/81471038-a71a8b00-91ee-11ea-822e-4627be378784.png)
And it broke after several times teleporting through it.

I'll disable this protection on the skyblock game. It's not really necessary anyway since players can easily teleport to their island by commands.

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
