### ISSUE TITLE
[Feature Request+Bug report] Cooldown on Notifications

### ISSUE THREAD

**Issue by jpenilla** [dniym/IllegalStack#40]
As noted in the wiki, the option to notify instead of blocking is very spammy. My use case is that I would like to allow TNT duping on a small scale. I want to be notified if a TNT duper exists, but not every time that it runs.  A possible solution could be to notify the first time the duper goes off, and then mute any duper at the same location for a configurable amount of time? ie 5 mins. This way it would notify again if it is still running after five minutes, and multiple dupers or a flying moving duper would still spam the admin. 

This part is a separate issue: I have noticed that TNT dupers are blocked/notified when PreventRailDupe is ON but PreventIndirectTNTPowerDupe is OFF. This means to allow TNT duping both have to be OFF, meaning you cannot independently allow them, they are linked. Edit: It also seems PreventIndirectTNTPowerDupe is unable to be set to notify only, even when on the notify only list it blocks duping.

**Comment by dniym** [comment]
Could you show me the type of tnt duping machine that the rail/carpet duper protection triggers on?  I mean if it's one that would also dupe rails that's why its getting detected.

**Comment by jmanpenilla** [comment]
Here is a video example
[video](https://youtu.be/CInszjDkVR4)
The TNT dupe detection is off, but when I turn it on it actually doesn't detect this duper, only the rail protection does.

**Comment by dniym** [comment]
Yeah this is because the detection you’re referring to checks for tnt duper’s that work by indirectly powering the tnt block.   Ones like shown in the video directly power the tnt block. 

https://github.com/dniym/IllegalStack/wiki/PreventIndirectTNTPowerDupe

**Comment by jmanpenilla** [comment]
![2020-06-04_20 18 48](https://user-images.githubusercontent.com/11360596/83833387-ae736e00-a6a0-11ea-8b99-69756ec17f62.png)
I modified it to be the same as the one in the video and it still gives rail dupe detection notifications

**Comment by dniym** [comment]
That’s going to trigger the rail dupe detection regardless because you’re pushing a powered rail attached to a slime block

**Comment by jmanpenilla** [comment]
So from what I understand there isn't a practical way to distinguish between when the rail or TNT dupe bug happens? If that's the case it's understandable I just wonder what TNT duper would trigger the indirecttntpowerdupe but not the rail dupe detection, so I could possibly use it in my world
