### ISSUE TITLE
 Unsafe enchantments?

### ISSUE THREAD

**Issue by andrewh4569** [dniym/IllegalStack#43]
Hello. Basically I use unsafe enchantments with tim the enchater and such, and I wasn't sure exactly if this plugin removes enchants like prot 8 etc.

**Comment by dniym** [comment]
It can disable them but that protection is not enabled by default. 

https://github.com/dniym/IllegalStack/wiki/FixIllegalEnchants

**Comment by andrewh4569** [comment]
Thank you!
