### ISSUE TITLE
Bug: books are stackable but get removed

### ISSUE THREAD

**Issue by jordanwilliams1** [dniym/IllegalStack#45]
books are stackable up to 64 but the plugin detects it as an 'ilegalstack' and removes it. Please can you fix this?

**Comment by dniym** [comment]
Written book only stacks to 16, like enderpearls and snowballs. 

https://minecraft.gamepedia.com/Written_Book

And only if the books are exactly the same.

**Comment by dniym** [comment]
If you would like for IllegalStack to ignore written books it can be done with a simple command.  

https://github.com/dniym/IllegalStack/wiki/AllowStack

**Comment by jordanwilliams1** [comment]
@dniym Thanks. I just doubled checked and I meant normal books. https://minecraft.gamepedia.com/Book

**Comment by jordanwilliams1** [comment]
Closed this. I need to test this. Wasn't as simple as I first thought.
