### ISSUE TITLE
Portals and disguised players

### ISSUE THREAD

**Issue by x1p** [dniym/IllegalStack#46]
When disguised with LibsDisguises, you can see yourself as a mob (selfview)
It's technically like a mob is following you while you are vanished. Or something like that.

When you try to pass through a nether portal, you get stuck on the destination side of the portal. The mob is not allowed to pass due to illegalstack preventing all mobs from going through portals.

It would be nice if illegalstack can see the difference between normal mobs and mobs created by LibsDisguises so a disguised player can still pass.

**Comment by dniym** [comment]
I can probably do that I’ll have to contact the dev to see if there’s a way to identify a disguised mob

**Comment by dniym** [comment]
Hmm, just working on this and even with the protection totally turned off I get stuck.   I also tried with IllegalStack totally unloaded and still got stuck when going through a portal disguised.

Hence I don't think illegalstack is the cause of this issue.

**Comment by x1p** [comment]
You're right. I should have tested this scenario.
