### ISSUE TITLE
IllegalStack doesn't remove orphan piston base

### ISSUE THREAD

**Issue by FrankHeijden** [dniym/IllegalStack#48]
Orphan piston base doesn't get removed, following [this tutorial](https://minecraft.gamepedia.com/Tutorials/Breaking_bedrock#Breaking_bedrock) (Step 1-8 is sufficient to get a single piston head to explode):
![2020-05-28_13 28 49](https://user-images.githubusercontent.com/22407829/83136240-7049dd80-a0e7-11ea-8ccf-1974e43c9fb6.png)

Using IllegalStack 2.1.2d:
```
> plugins
[13:31:23 INFO]: Plugins (1): IllegalStack
```
```
> ver
[13:31:49 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:31:49 INFO]: Previous version: git-Paper-267 (MC: 1.15.2)
[13:31:49 INFO]: You are running the latest version
```

**Comment by FrankHeijden** [comment]
Seems to me like an off-by-one error:
![2020-05-28_13 34 58](https://user-images.githubusercontent.com/22407829/83136709-3a592900-a0e8-11ea-9de1-4336f7f26b11.png)

**Comment by dniym** [comment]
It looks like you've teleported right on top of the offending piston.  Which is the piston that I assume the head is missing from.  Is this still an issue in the current version??  2.1.3c
