### ISSUE TITLE
Only have question 

### ISSUE THREAD

**Issue by johnneijzen** [dniym/IllegalStack#55]
because of paper already fix Donkey Dupe and 0 tick farm dupe and now fix tnt dupers
https://github.com/PaperMC/Paper/pull/3544

is safe to just disable them in illegalstacks now?

**Comment by respiter** [comment]
yeah

**Comment by dniym** [comment]
Paper also fixed the ability to desync chested animals and dupe with them?  And portal duping?

**Comment by johnneijzen** [comment]
> Paper also fixed the ability to desync chested animals and dupe with them? And portal duping?

which one you mean portal entity dupe or falling block dupe i think desync chested animals fixed i remember this commit "lot
of dupe bugs in general around nether portals and entity world transfer" https://github.com/PaperMC/Paper/commit/a6ac47e502d4cadef0c2c289956971739076c49c

i wonder what is not yet patched in paper aside from carpet dupe + rail dupe and falling block dupe
that Spottedleaf is planning to patch soon https://github.com/PaperMC/Paper/pull/3550
