### ISSUE TITLE
Netty error

### ISSUE THREAD

**Issue by Momonche** [dniym/IllegalStack#58]
Hello,
This error sometimes appear and make a KeepAlive Timedout for some players
Not sure it's an IllegalSatck issue but seems to be

https://pastebin.com/YchtVVsi

**Comment by dniym** [comment]
Can you verify if this issue still exists in version 2.1.7b+ ?

**Comment by Momonche** [comment]
It's a very rarely issue, I'll open a new issue if I see this again
Not sure it's come from IllegalStack
