### ISSUE TITLE
Personnal Request: Residence "/res set" Menu have problems with FixIllegalEnchants

### ISSUE THREAD

**Issue by eternitymoe** [dniym/IllegalStack#6]
FixIllegalEnchants will try to fix items in the "/res set" Menu
<img width="434" alt="Screenshot 2019-12-01 at 13 46 57" src="https://user-images.githubusercontent.com/44344308/69910124-18d0fa80-1441-11ea-9cc2-fbd0c46ee0d2.png">
<img width="477" alt="Screenshot 2019-12-01 at 13 47 02" src="https://user-images.githubusercontent.com/44344308/69910126-19699100-1441-11ea-9b86-7848a495d32d.png">

**Comment by dniym** [comment]
Could you try a /res set then check the console and copy/paste the [IllegalStack] messages?  I assume its removing/fixing enchants that are not supposed to be on those items.     Also what is the title of that GUI window?  Once you provide me with that information I should be able to look at making the two plugins play nice together.

**Comment by In77** [comment]
**Console message:**
[21:57:29 INFO]: [IllegalStack] -Could not fix Enchantment LUCK.(1) on END_PORTAL_FRAME found on player: bakamoe this enchantment is not valid for this item type!
<img width="967" alt="Screenshot 2019-12-02 at 22 04 32" src="https://user-images.githubusercontent.com/44344308/69965680-bc103580-154f-11ea-92d1-95e99198e3c2.png">

**You can download a free copy of Residence in here**
https://zrips.net/Residence/

**/res set GUI window title is not fixed**
title in /res set is "Res-name flags"
in /res pset is "Player-name Res-name flags"
<img width="319" alt="Screenshot 2019-12-02 at 22 01 29" src="https://user-images.githubusercontent.com/44344308/69965473-4e640980-154f-11ea-9603-83a3c91179b0.png">

**At the same time, the title will change according to the language set by the RES plugin.**
This is the GUI in Chinese (All flags are shown)
<img width="270" alt="Screenshot 2019-12-02 at 22 05 18" src="https://user-images.githubusercontent.com/44344308/69965764-ebbf3d80-154f-11ea-8290-7b1d2c422027.png">

**Comment by In77** [comment]
So you may be able to temporarily not detect this when the player uses the "/ res set" command and called the event that opens the GUI?

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
