### ISSUE TITLE
Overstack permissions issue.

### ISSUE THREAD

**Issue by DontStarve72** [dniym/IllegalStack#62]
The illegalstack.overstack permission does not allow for the bypass of the items in the RemoveItemsOfType list.

**Comment by dniym** [comment]
It does not, the pemission IllegalStack.Overstack really only applies to overstacked items.

**Comment by DontStarve72** [comment]
Could I turn this into a feature request for a permission that does?

**Comment by dniym** [comment]
will be added ass of 2.1.7c
