### ISSUE TITLE
Wither Summoning

### ISSUE THREAD

**Issue by gecko10000** [dniym/IllegalStack#63]
Would it be possible to make withers only summonable when they are built upright, or for ones built sideways or upside-down to be moved down some blocks?

**Comment by dniym** [comment]
maybe.   what purpose would that server? making them harder to trap?

**Comment by levtey** [comment]
Exactly, make it so people have to fight the wither legit, no option to trap in bedrock and kill

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
