### ISSUE TITLE
BlockBadItemsFromCreativeTab

### ISSUE THREAD

**Issue by thecenters** [dniym/IllegalStack#64]
I have this enabled but I need a way for admins to bypass this limitation. Currently none of the permissions with the plugin allow that.

**Comment by dniym** [comment]
Opped players bypass this permission, do you want players with the illegalstack.admin perm to bypass this?

**Comment by dniym** [comment]
as soon as 1.2.7c is released players with the illegalstack.admin permission will also bypass this check in addition to opped players.
