### ISSUE TITLE
ShopGUI+ issue

### ISSUE THREAD

**Issue by kinrokinro** [dniym/IllegalStack#65]
![Screenshot_549](https://user-images.githubusercontent.com/3493914/87720142-2616db80-c7bd-11ea-8f0d-6ab1c6b8fb90.png)
1.15.2 paper-378, istack 2.1.6

**Comment by dniym** [comment]
IllegalStack is doing exactly what it’s supposed to do.    The maximum stack size for eggs is 8 and 1 for rabbit stew.  

See this wiki page for more information and to learn how to whitelist specific items. 
https://github.com/dniym/IllegalStack/wiki/RemoveOverstackedItems

**Comment by dniym** [comment]
Edit:    ShopguiPlus also has an option in the config to unstack items which will prevent this from happening.
