### ISSUE TITLE
i want oped players to be able to accses god items but i cant find a way to in the config some one please help me

### ISSUE THREAD

**Issue by niiiiggggaaa** [dniym/IllegalStack#66]
i want oped players to be able to accses god items but i cant find a way to in the config some one please help me

**Comment by dniym** [comment]
Like illegally enchanted ones? Which specific protection is triggering?

**Comment by niiiiggggaaa** [comment]
all of it the enchatments and ilegal stacker trigger when a player is oped

**Comment by dniym** [comment]
/istack value add AllowStackForGroup *   - will bypass the overstack protection for all opped players or any player with the IllegalStack.OverStack permission


/istack toggle AllowBypass - Allows players with the illegalstack.enchantbypass permission to possess items with Illegal enchantments

**Comment by niiiiggggaaa** [comment]
where do i find the permissions

**Comment by dniym** [comment]
https://github.com/dniym/IllegalStack/wiki/Commands-and-Permissions

**Comment by niiiiggggaaa** [comment]
tnx

**Comment by niiiiggggaaa** [comment]
ok i feel really dumb where do i put this?

**Comment by dniym** [comment]
Just run those commands in game or from the console, no restart or reload required if you do it that way.  

If you edit config.yml manually you MUST do/istack reload (in game/console) BEFORE restarting the server

**Comment by niiiiggggaaa** [comment]
i can do totems but i cant do disable enchants for oped players

**Comment by niiiiggggaaa** [comment]
the bypass enchant was on but was still unenchanting stuff even tho i was oped

**Comment by dniym** [comment]
send me your config.yml via pastebin?

**Comment by niiiiggggaaa** [comment]
sorry for the late reply here you go 🙂

**Comment by dniym** [comment]
Do not see a link?

**Comment by niiiiggggaaa** [comment]
what do you mean?

**Comment by niiiiggggaaa** [comment]
i uploaded a file

**Comment by dniym** [comment]
Must not be able to see it on mobile.. have to look when I get home
