### ISSUE TITLE
Customizable Armor Stands datapack problem

### ISSUE THREAD

**Issue by Furuss** [dniym/IllegalStack#7]
Hello, your plugin is awsome but it does not work with Customizable Armor Stands datapack by Xisumavoid. When i spawn an armor stands book it works as intended. But when i try to work with it for a while, i get chat error: [Illegal STack] - Unknown and my books content changes to: *Illegal book tag*. Please help :(

**Comment by dniym** [comment]
I'm betting the datapack creates or edits a book and for some reason removes the author..   There shouldn't ever be a missing author on a written book.   I would suggest sending the data packs author a message and see if they can make sure their datapack does not create a book without giving it an author.    That or turn off Oversized Chunk Dupe Protection with:  /istack toggle RemoveBooksNotMatchingCharset

**Comment by Furuss** [comment]
Hello. I messaged the author as you suggested. For now, your solution worked. Thank you!
