### ISSUE TITLE
[Bug] Using Hacked Client AutoMount Allows Bypassing Dupe Bug Fix

### ISSUE THREAD

**Issue by pinkpig3777** [dniym/IllegalStack#70]
Today a dupe bug occurred on the server (I am temporarily helping out on) even though IllegalStack was added.

Admittedly, the version of IllegalStack was probably very outdated so please let me know if this has been fixed in later versions. I have since updated to the latest version but I can't test the bug myself.
 
After the player duped and was banned, his friend logged into the Discord server pretending he didn't know the banned player. Shortly after he came clean and told me how his friend did it.

**Steps to Reproduce:**
1. Be on a 1.14.4 paper server with IllegalStack installed.
2. https://gyazo.com/541208edac2553626951b7e8cecc4680

**Comment by pinkpig3777** [comment]
Oh also he said "it was actually the plugin that causes this dupe bug". 

Although I suppose it doesn't matter because without the plugin there'd still be a dupe bug (that is easier to use). :P

**Comment by dniym** [comment]
Yeah old version definitely that was fixed back in april

**Comment by pinkpig3777** [comment]
> 
> 
> Yeah old version definitely that was fixed back in april

Ah okay, great. Thanks! :)
