### ISSUE TITLE
PreventTripwireDupe removes complete stack in the inventory

### ISSUE THREAD

**Issue by x1p** [dniym/IllegalStack#72]
I have TripwireDupe enabled. When the player tries to place a tripwire hook against a trapdoor or even next to a trapdoor.
![Screenshot_20200720_210420](https://user-images.githubusercontent.com/28690790/87976017-b199b080-cacc-11ea-916f-fcf97dac5b95.png)
Is it really necessary to remove a tripwire_hook next to a trapdoor?

I noticed that the whole stack tripwire hooks is removed from the players inventory.
I understand that the involved tripwire is removed, but why do the 63 other tripwires need to be removed from the inventory of the player?

**Comment by x1p** [comment]
Any update on this? It's still present.
That the check is a bit rough, I fully understand.
But why delete all remaining tripwires from the players' inventory?

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
