### ISSUE TITLE
Baby Piglin 1.16.2 Dupe Glitch

### ISSUE THREAD

**Issue by BetaBurnt** [dniym/IllegalStack#78]
Video explaining it (it's stupid easy) - https://www.youtube.com/watch?v=8nZNlj_xrJ0

Should be blockable by disabling baby piglins ability to pick things up if nothing else

**Comment by dniym** [comment]
Yeah known issue, appears to only affect spigot servers, paper and other variants are not affected.  I’ll push out a fix this eve for regular spigot users.

**Comment by dniym** [comment]
Fixed as of 2.1.9b


https://github.com/dniym/IllegalStack/wiki/PreventPiglinDupe
