### ISSUE TITLE
End crystal generation on towers after spawning a dragon results in "Prevented a bed from being used as an explosive"

### ISSUE THREAD

**Issue by CW-UK** [dniym/IllegalStack#79]
As the title suggests, when the End Crystals are spawning on top of the towers in The End after summoning a dragon using the exit portal, I receive these messages from IllegalStack.

![image](https://user-images.githubusercontent.com/6217127/91554113-645bfa80-e926-11ea-956d-ce75ea6ed1c0.png)

**Comment by dniym** [comment]
Ah Hmmm I’ll do some testing on this thanks for reporting

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
