### ISSUE TITLE
Is it possible to fix the bookban vulnerability?

### ISSUE THREAD

**Issue by roy20001215** [dniym/IllegalStack#8]
[](https://www.youtube.com/watch?v=_7f6DojmoWE)

Just like in the video, as long as you get 3 shulkerbox books filled with Chinese characters, you may disconnect the player, because many people on my server banned others like this, thank you

**Comment by roy20001215** [comment]
https://www.youtube.com/watch?v=_7f6DojmoWE

**Comment by dniym** [comment]
IllegalStack will prevent players from using unicode characters in books.    It will restrict all books to a specific character set for regular players.   (Defaults to USASCII)     Unless you have the chinese charset enabled on your server there should be no way for regular players to create chinese books.

**Comment by dniym** [comment]
Closed due to no response from author, if still having issues please re-open ticket.
