### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for IllegalStack

### ISSUE THREAD

**Issue by IITFA** [dniym/IllegalStack#89]
https://pastebin.com/raw/TWSEvM2S

Been noticing this error.

ProtocolLib 4.5.1
IllegalStack 2.2.0e

Server 1.12.2 CatServer-eb3ed0a-universal

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
