### ISSUE TITLE
Disable "KickForAutoClickerFishing" still kick player

### ISSUE THREAD

**Issue by WMGameLive** [dniym/IllegalStack#9]
Server Version: 1.14.4

I turn "KickForAutoClickerFishing" to "false" in config or use command "/istack toggle KickForAutoClickerFishing" to disable it, but it still kick the player who use AutoClicker to fishing.

**Comment by dniym** [comment]
What message is being sent to the console when the player is kicked?  Just tried verifying this and the protection disables/enables as expected with /istack toggle KickForAutoClickerFishing..    NOTE: if you modify the config.yml you MUST use /istack reload BEFORE you restart the server or config changes will be lost.

**Comment by WMGameLive** [comment]
i will try again later

**Comment by dniym** [comment]
Any update on this issue?

**Comment by dniym** [comment]
Closing due to no response from author, if still having issues please re-open ticket.
