### ISSUE TITLE
Dragon Respawn Bug

### ISSUE THREAD

**Issue by XANT3R** [dniym/IllegalStack#90]
When we respawn a dragon by crystals in the end world, this illegalstack detects this as blowing up the beds.

[14:20:45 INFO]: [IllegalStack] -Prevented a bed from being used as an explosive @Location{world=Cra
World{name=world_the_end},x=-13.0,y=103.0,z=-40.0,pitch=0.0,yaw=0.0}

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
