### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot drop air

### ISSUE THREAD

**Issue by x1p** [dniym/IllegalStack#91]
Error:
https://pastebin.com/raw/iP7aTd5t

Situation:
![Screenshot_20201011_155021](https://user-images.githubusercontent.com/28690790/95680377-8610f880-0bd9-11eb-9114-2fc61defa4f5.png)

IllegalStack v2.2.0e
Paper 1.16.3 (fork)

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
