### ISSUE TITLE
AllowBypass is broken on 1.16.3

### ISSUE THREAD

**Issue by TheForgottenKing** [dniym/IllegalStack#92]
I have AllowBypass enabled in config.yml and FixIllegalEnchantments enabled, but upon trying to enchant an item illegally the enchantments are reset anyway.

Minecraft Version: 1.16.3
Software: Paper
Version: Newest from spigot

**Comment by dniym** [comment]
Whenever you edit config.yml manually you MUST do /istack reload BEFORE RESTARTING the server 

Alternatively you can use the in game commands /istack prot to toggle them without reloading the config or restarting the server.

**Comment by TheForgottenKing** [comment]
I have done that. 
![image](https://user-images.githubusercontent.com/7876205/96775536-4605fe80-13ad-11eb-9d75-829edf413574.png)
Allow Bypass is enabled
![image](https://user-images.githubusercontent.com/7876205/96775575-55854780-13ad-11eb-8c14-e2e516b9b3d0.png)
But this still happens

**Comment by dniym** [comment]
It says right at the top of that menu that “[ON] Fix Illegal Enchantment Levels”

Click the word ON, it will toggle off

**Comment by TheForgottenKing** [comment]
I want the protection on, but I want to be able to bypass it with op. Is this possible?

**Comment by dniym** [comment]
IllegalStack version 2.8 is now out, if you are still experiencing this issue please open a new ticket.
